const { SitemapStream, streamToPromise } = require("sitemap");
const { Readable } = require("stream");

export default async (req, res) => {
  // An array with your links
  const links = [
    { url: "https://tutorial.learnbay.co/", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/MongoDB/1-getting-started", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/MongoDB/2-Mongodb-database", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/MongoDB/3-mongodb-datatype-and-documents", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/MongoDB/4-mongodb-indexing-and-aggregation", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/MongoDB/5-mongodb-tools-and-structure", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/PowerBI/1-getting-started", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/PowerBI/2-power-bi-data-modelling", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/PowerBI/3-power-bi-components", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/PowerBI/4-key-features-of-dax", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/PowerBI/5-power-bi-dashboard", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/PowerBI/6-power-bi-charts", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/PowerBI/7-power-bi-slicers", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/PowerBI/8-power-bi-filters", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Python/1-getting-started", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Python/2-python-getting-started", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Python/3-python-syntax", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Python/4-python-comment", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Python/5-string-formatting-in-python", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Python/6-data-types-in-python", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Python/7-python-variables", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Python/8-boolean-data-types-in-python", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Python/9-python-operators", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Python/10-python-strings", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Python/11-python-list", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Python/12-python-tuples", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Python/13-python-sets", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Python/14-python-dictionary", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Python/15-python-iterators", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Python/16-python-if-else", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Python/17-python-loops", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Python/18-python-functions", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Python/19-python-map", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Python/20-python-lambda", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Python/21-python-filter", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Python/22-python-regular-expression", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Python/23-python-exception-handling", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Python/24-python-file-handling", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Python/25-python-numpy", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Python/26-python-pandas-library", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Python/27-python-scipy", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Python/28-python-matplotlib", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Python/29-python-seaborn", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/SQL/1-getting-started", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/SQL/2-sql-installation-structure-and-commands", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/SQL/3-sql-data-types-and-operators", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/SQL/4-sql-clauses", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/SQL/5-sql-joins", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/SQL/6-sql-database", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/SQL/7-sql-constraints", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/SQL/8-sql-functions", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/SQL/9-normalization-in-sql", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/SQL/10-sql-statements", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Statistics/1-getting-started", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Statistics/2-correlation-between-statistics-and-data-science", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Statistics/3-probability-distributed-function", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Statistics/4-the-basics-of-cumulative-distribution", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Statistics/5-the-basic-of-conditional-probability", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Statistics/6-the-basics-of-bayes-theorem", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Statistics/7-the-basics-of-population-vs-sample", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Statistics/8-the-basics-of-sample-size", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Statistics/9-the-basics-of-simple-random-sampling", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Statistics/10-the-basics-of-systematic-sampling", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Statistics/11-the-basics-of-cluster-sampling", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Statistics/12-the-basics-of-convenience-sampling", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Statistics/13-the-basics-of-quota-sampling", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Statistics/14-the-basics-of-snowball-sampling", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Statistics/15-the-basics-of-judgment-sampling", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Statistics/16-the-basic-types-of-statistical-variables", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Statistics/17-the-basics-of-box-plot-and-five-number-summary", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Statistics/18-the-basics-of-outliers", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Statistics/19-the-basics-of-the-iqr-method", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Statistics/20-the-basics-of-the-z-score-method", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Statistics/21-measures-of-central-tendency", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Statistics/22-measures-of-dispersion-standard-deviation-variance-range", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Statistics/23-introducing-measures-of-skewness", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Statistics/24-the-basics-of-measures-of-variability-shape-kurtosis", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Statistics/25-the-basics-of-central-limit-theorem", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Statistics/26-the-basics-of-point-and-interval-estimation", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Statistics/27-the-basics-of-confidence-interval", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Statistics/28-the-basics-of-z-distribution", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Statistics/29-the-basics-of-t-distribution", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Statistics/30-the-basics-of-rejection-region", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Statistics/31-the-basics-of-type-of-tests", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Statistics/32-the-basics-of-type-and-errors", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Statistics/33-the-basics-of-the-p-value-method", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Statistics/34-the-basics-of-the-chi-square-test", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Statistics/35-the-basics-of-the-regression", changefreq: "daily", priority: 0.3 },
    { url: "https://tutorial.learnbay.co/Statistics/36-the-basics-of-factorial-analysis-of-variance", changefreq: "daily", priority: 0.3 },

  ];

  // Create a stream to write to
  const stream = new SitemapStream({ hostname: `https://${req.headers.host}` });

  res.writeHead(200, {
    "Content-Type": "application/xml",
  });

  const xmlString = await streamToPromise(
    Readable.from(links).pipe(stream)
  ).then((data) => data.toString());
  res.end(xmlString);
};